# html lang
language: zh

# main menu navigation
# icon use ionicons
# Link：https://ionicons.com/
menu:
  home:
    icon: home
    src: /
  about:
    icon: person
    src: /about
  archives:
    icon:  archive
    src: /archives
  categories:
    icon: layers
    src: /categories
  tags:
    icon: pricetags
    src: /tags
    

link:
  Github:
    icon: /icon/github.png
    src:
  Twitter:
    icon: /icon/twitter.png
    src:

home_img: /home_bg.jpg

footer:
  since: 2018

# Gitalk
gitalk:
  enable: true # true
  clientID: 30daf96e536313585e82 # GitHub Application Client ID
  clientSecret: c380eff4277e1a8e3efabd5fe82074c019d0ede9 # Client Secret
  repo: korilin.cn.github.io # Repository name
  owner: korilin # GitHub ID
  admin: korilin # GitHub ID

highlight:
  enable: true
  style: tomorrow

prism:
  enable: false

# stylesheets loaded in the <head>
stylesheets:
  - /css/particle.css

# scripts loaded in the end of the body
scripts:
  - /js/particle.js
