# html lang
language: zh

# icon use ionicons
# Link：https://ionicons.com/

# main menu navigation
menu:
  home:
    icon:
      type: home
      theme: filled
    src: /
  about:
    icon:
      type: home
      theme: filled
    src: /about
  archives:
    icon:
      type: home
      theme: filled
    src: /archives
  categories:
    icon:
      type: home
      theme: filled
    src: /categories
  tags:
    icon:
      type: home
      theme: filled
    src: /tags
  英文博客:
    icon:
      type: home
      theme: filled
    src: https:en.korilin.com

head_img: /images/avatar.png
home_img: /home_bg.jpg

footer:
  since: 2018
  ICP:
    enable: true
    code: 粤ICP备19149652号

# Gitalk
gitalk:
  enable: true # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

  # theme style: full / night , defalut: full
style: full

# scripts loaded in the end of the body
scripts:
  - /js/particle.js
