# html lang
language: zh

# icon use ionicons
# Link：https://ionicons.com/

# main menu navigation
menu:
  home:
    icon: home
    src: /
  about:
    icon: person
    src: /about
  archives:
    icon: library
    src: /archives
  categories:
    icon: layers
    src: /categories
  tags:
    icon: pricetags
    src: /tags
  英文博客:
    icon: trail-sign
    src: https:en.korilin.com

head_img: /images/avatar.png
home_img: /home_bg.jpg

footer:
  since: 2018
  ICP:
    enable: true
    code: 粤ICP备19149652号

# Gitalk
gitalk:
  enable: true # true
  clientID: 30daf96e536313585e82 # GitHub Application Client ID
  clientSecret: c380eff4277e1a8e3efabd5fe82074c019d0ede9 # Client Secret
  repo: korilin.cn.github.io # Repository name
  owner: korilin # GitHub ID
  admin: korilin # GitHub ID

  # theme style: full / night , defalut: full
style: full
  
# scripts loaded in the end of the body
scripts:
  - /js/particle.js
